name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi! Thanks for creating your first issue at Oloid. Hope you followed the guidelines.'
        pr-message: 'Congratulations! Thanks for making your first PR at Oloid. The Project Maintainers will review it soon.'